writetable(testData{1},'testData01.csv')
writetable(testData{2},'testData02.csv')
writetable(testData{3},'testData03.csv')
writetable(testData{4},'testData04.csv')
writetable(testData{5},'testData05.csv')
writetable(testData{6},'testData06.csv')
writetable(testData{7},'testData07.csv')
writetable(testData{8},'testData08.csv')
writetable(testData{9},'testData09.csv')
writetable(testData{10},'testData10.csv')


writetable(trainData{1},'trainData01.csv')
writetable(trainData{2},'trainData02.csv')
writetable(trainData{3},'trainData03.csv')
writetable(trainData{4},'trainData04.csv')
writetable(trainData{5},'trainData05.csv')
writetable(trainData{6},'trainData06.csv')
writetable(trainData{7},'trainData07.csv')
writetable(trainData{8},'trainData08.csv')
writetable(trainData{9},'trainData09.csv')
writetable(trainData{10},'trainData10.csv')
